#!/usr/bin/python2.7
#
#    Versat Assembler (va)
#

import sys, string

from math import ceil

import os.path

class vaError(Exception):
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

lookup={}

error = 0

def getVal (s) :
    "return numeric value of a symbol or number"
    if not s : return 0       # Empty symbol - zero
    a = lookup.get(s)         # Get value or None if not in lookup
    if a == None :
        if s[:2] == "0x" or s[:2] == "0X":
            b = int(s, 16) # hex number
        elif s[0] == "\'" and s[2] == "\'":
            b = ord(s[1]) # char
            print b
        elif s == "\'\\n\'":
            b = ord('\n') # char
        elif s == "\'\\r\'":
            b = ord('\r') # char
        else :
            b = int(s)  #decimal a number
        a = b
        if b < 0 :
            a = 2**lookup.get("IMM_W") + b
    return a

def pass1 (program,PC) :
    "determine addresses for labels and add them to the lookup dictionary"
    global lookup
    for lin in program :
        flds = string.split(lin)
        if not flds : continue        # just an empty line
        if lin[0] == '#' : continue   # a comment line
        if lin[0] > ' ' :             # a symbol. Save its address in lookup
            symb = flds[0]            
            lookup[symb] = PC
            if len(flds) > 1 :        # advance program counter unless only a symbol
                PC = PC + 1
                print PC, flds[0]
        elif flds and flds[0] != '#' :
            PC = PC + 1
            print PC, flds

def assemble (flds, PC) :
    "assemble instruction to machine code"
    global lookup
    parts = flds[1:]
    if len(parts) == 1 and flds[0]==".memset" : return  getVal(parts[0])
    opval = lookup.get(flds[0])
    if opval == None : raise vaError(1)
    if len(flds) == 1 or flds[0]=="nop" : return opval*16**(lookup.get("INSTR_W")/4-1)
    if len(parts) == 1 and (flds[0]=="beqi" or flds[0]=="bneqi") :
        imm = getVal(parts[0])
        if (imm > 2**(lookup.get("IMM_W")-1)-1) or (imm < -2**(lookup.get("IMM_W")-1)) : raise vaError(2)
        if imm < 0 : imm = 2**lookup.get("IMM_W") + imm
        return opval*16**(lookup.get("INSTR_W")/4-1) + imm
    if len(parts) == 1 :
        temp = parts[0].split('>>',1)
        if len(temp) == 2 :
            parts[0] = str(getVal(temp[0]) >> int(temp[1]))
        if flds[0]=="ldi" and getVal(parts[0]) > 2**lookup.get("IMM_W")-1 : return opval*16**(lookup.get("INSTR_W")/4-1) + (getVal(parts[0])&(2**lookup.get("IMM_W")-1))
        if flds[0]=="ldih" and getVal(parts[0]) > 2**lookup.get("IMM_W")-1 : return opval*16**(lookup.get("INSTR_W")/4-1) + ((getVal(parts[0])&((2**lookup.get("IMM_W")-1)<<lookup.get("IMM_W")))>>lookup.get("IMM_W"))
        if getVal(parts[0]) > 2**lookup.get("IMM_W")-1 : raise vaError(2)
        return opval*16**(lookup.get("INSTR_W")/4-1) + getVal(parts[0])
    if len(parts) == 2 :
        if (getVal(parts[0]) + getVal(parts[1])) > 2**lookup.get("IMM_W")-1 : raise vaError(2)
        return opval*16**(lookup.get("INSTR_W")/4-1) + getVal(parts[0]) + getVal(parts[1])
    if len(parts) == 3 :
        if (getVal(parts[0]) + getVal(parts[1]) + getVal(parts[2])) > 2**lookup.get("IMM_W")-1 : raise vaError(2)
        return opval*16**(lookup.get("INSTR_W")/4-1) + getVal(parts[0]) + getVal(parts[1]) + getVal(parts[2])
    if len(parts) > 3 : raise vaError(2)
    

def pass2 (program, PC, fout) :
    global lookup
    global error

    "translate assembly code and symbols to machine code"

    instrFormatTerminal = "%0" + str(int(ceil((lookup.get("ADDR_W")+1)/4))) + "x %0" + str(int(ceil(lookup.get("INSTR_W")/4))) + "x\t%s"
    instrFormatFile = "0" + str(int(ceil(lookup.get("INSTR_W")/4.0))) + "x"

    j = 0
    for lin in program :
        lin2 = lin.lstrip()
        lin2 = lin.split('#', 1)[0] #ignore comment at the end of line 
        lin2 = lin2.replace(',', ' ') #remove commas
        lin2 = lin2.replace("\' \'", "0x20") #remove commas
        flds = string.split(lin2)
        if lin[0] == '#' : continue        # a comment line
        if lin[0] > ' ' : flds = flds[1:]  # drop symbol if there is one
        if not flds : continue             # don't print anything, it's a blank line
        else:
            try :
                instruction = assemble(flds, PC)
                fout.write(format(instruction, instrFormatFile)+"\n")
                print instrFormatTerminal % (PC, instruction, lin),
                PC = PC + 1
                j = j + 1
            except vaError as e:
                print "*********** %s" % lin,
                error = 1

    instruction = lookup.get("nop")*16**(lookup.get("INSTR_W")/4-1)
    # complete program file wint zeros (nps)
    if j > (2**lookup.get("ADDR_W")-1) :
        print "Program memory exceeded"
    else:
        while j < 2**(lookup.get("ADDR_W")-1) : 
            fout.write(format(instruction,instrFormatFile)+"\n")
            j = j + 1

def main () :
    global lookup
    
    #open symbol dictionary
    xdict = open('xdict.json','r');
    lookup = eval(xdict.read())
    
    # init program counter
    PC = 0

    if len(sys.argv) != 3:
        print "Usage: ./va infile outfile"
        sys.exit(1)
    else:
        infile = sys.argv[1]
        outfile = sys.argv[2]
    
    fin = open (infile, 'r')
    program = fin.readlines()
    pass1 (program, PC)

    fout = open (outfile, 'w')
    pass2 (program, PC, fout)
    fout.close()

    if (error == 1):
        print "Program has errors"

if __name__ == "__main__" : main ()
